# Generated by Django 5.0.6 on 2024-07-06 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('slug', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='اسلاگ')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخته شده')),
                ('is_published', models.BooleanField(default=False, verbose_name='ایا پابلیش شده')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='categories.category')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
    ]
