# Generated by Django 5.0.6 on 2024-07-06 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_remove_category_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created',
        ),
    ]
